### ISSUE TITLE
LogTest fails to run, denied permission.

### ISSUE THREAD

**Issue by julianharty** [ISNIT0/AndroidCrashDummy#1]
Revisiting this project after a year or so, I can't get the LogTest to run. Instead it's denied permission as the app does not have `READ_LOGS` permission (even though the permission was specified in the `AndroidManifest.xml` for the debug build).

I've spent about a day or so investigating where the issues are and finally decided it's worth writing this issue to keep track of the progress.

**Comment by julianharty** [comment]
Here's a summary of the many things I've checked and tried. I've finally reached the point where the tests can run i.e. they have permission, however they now fail with a new reason :)

I discovered it is possible to add an AndroidManifest for the Android Tests, there's an example in one of Google's old projects https://github.com/google/libaddressinput/ Sadly that project is no longer current and needs significant work to actually get the project to build and then run the tests. I provided some notes to one of the issues on that topic: https://github.com/google/libaddressinput/issues/179

Apparently it's been possible to join two Android binaries through a shared id (this support is now deprecated) which offered the promise of being able to inherit permissions from shared binaries. I spent some time exploring that approach but didn't end up implementing it.

LinkedIn TestButler project https://github.com/linkedin/test-butler and https://github.com/sebaslogen/Blendletje/ which built on the test-butler foundations are also interesting, however they're limited to working on stock Android emulator images so serve a relatively narrow audience (and yet may still be worth returning to as an approach for running our tests in emulators in CI pipelines).

I also visited https://github.com/JeroenMols/MockitoExample and read https://speakerdeck.com/jeroenmols/testing-made-sweet-with-a-mockito (now out of date given the many changes to Mockito, some described in his article https://jeroenmols.com/blog/2017/01/17/mockitoandroid/)

The following series of `adb` commands combine those used by gradle when running the connectedAndroidTest task together with various checks of permissions of the apk files on the device before and after explicitly granting the READ_LOGS permission (thanks to https://tasker.joaoapps.com/userguide/en/help/ah_read_logs_grant.html) 
```
adb shell pm list packages -3

adb install ./app/build/outputs/apk/debug/app-debug.apk
adb install ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
adb shell pm list packages -3

adb shell dumpsys package com.example.user.androidtestapp.test
adb shell dumpsys package com.example.user.androidtestapp

adb shell pm grant com.example.user.androidtestapp.test android.permission.READ_LOGS
adb shell pm grant com.example.user.androidtestapp android.permission.READ_LOGS

adb shell dumpsys package com.example.user.androidtestapp.test
adb shell dumpsys package com.example.user.androidtestapp

adb shell am instrument -w -r   com.example.user.androidtestapp.test/android.support.test.runner.AndroidJUnitRunner
```

The test still fails, as follows, however it's now possible to run it!
```
Julians-MBP:AndroidCrashDummy julianharty$ adb shell am instrument -w -r   com.example.user.androidtestapp.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: class=com.example.user.androidtestapp.ExampleInstrumentedTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=2
INSTRUMENTATION_STATUS: stream=
com.example.user.androidtestapp.ExampleInstrumentedTest:
INSTRUMENTATION_STATUS: test=useAppContext
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: class=com.example.user.androidtestapp.ExampleInstrumentedTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=2
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: test=useAppContext
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_STATUS: class=com.example.user.androidtestapp.LogTest
INSTRUMENTATION_STATUS: current=2
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=2
INSTRUMENTATION_STATUS: stream=
com.example.user.androidtestapp.LogTest:
INSTRUMENTATION_STATUS: test=clickLog100Button
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: class=com.example.user.androidtestapp.LogTest
INSTRUMENTATION_STATUS: current=2
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=2
INSTRUMENTATION_STATUS: stack=java.lang.Exception: Not Implemented, logsString has length: [22698]
	at com.example.user.androidtestapp.LogTest$1.customHandler(LogTest.java:30)
	at xyz.reeve.logassert.LogAssert.assertLogsCustom(LogAssert.java:29)
	at com.example.user.androidtestapp.LogTest.clickLog100Button(LogTest.java:36)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
	at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

INSTRUMENTATION_STATUS: stream=
Error in clickLog100Button(com.example.user.androidtestapp.LogTest):
java.lang.Exception: Not Implemented, logsString has length: [22698]
	at com.example.user.androidtestapp.LogTest$1.customHandler(LogTest.java:30)
	at xyz.reeve.logassert.LogAssert.assertLogsCustom(LogAssert.java:29)
	at com.example.user.androidtestapp.LogTest.clickLog100Button(LogTest.java:36)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
	at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

INSTRUMENTATION_STATUS: test=clickLog100Button
INSTRUMENTATION_STATUS_CODE: -2
INSTRUMENTATION_RESULT: stream=

Time: 0.993
There was 1 failure:
1) clickLog100Button(com.example.user.androidtestapp.LogTest)
java.lang.Exception: Not Implemented, logsString has length: [22698]
	at com.example.user.androidtestapp.LogTest$1.customHandler(LogTest.java:30)
	at xyz.reeve.logassert.LogAssert.assertLogsCustom(LogAssert.java:29)
	at com.example.user.androidtestapp.LogTest.clickLog100Button(LogTest.java:36)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
	at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

FAILURES!!!
Tests run: 2,  Failures: 1


INSTRUMENTATION_CODE: -1
```

**Comment by julianharty** [comment]
Looks like our code from 2017 needed to be revised (or possibly a new approach devised) because of changes and restrictions in Android releases e.g. see 

* https://stackoverflow.com/a/45270606/340175 
* https://stackoverflow.com/a/16795874/340175
* https://groups.google.com/g/android-developers/c/6U4A5irWang/m/AvZsrTdfICIJ (a long and detailed explanation that includes an explanation of how we can set the permission explicitly).

**Comment by julianharty** [comment]
Some more interesting ideas to explore 

- https://stackoverflow.com/questions/38586678/grant-access-mock-location-permission-for-testing-using-adb-fails-in-marshmallow/ 
- https://stackoverflow.com/questions/11420845/android-checkcallingorselfpermission-not-returning-properly

**Comment by julianharty** [comment]
And yet another article, this time where someone's trying to grant a permission in a Travis-CI job https://travis-ci.community/t/how-can-i-add-mock-location-permission-to-android-jobs/6162

**Comment by julianharty** [comment]
More things I've tried...

- To use a GrantPermissionRule. See https://flank.github.io/flank/#android-code-coverage for the inspiration. I then ran into errors similar to 
    - https://stackoverflow.com/questions/53595837/androidx-no-instrumentation-registered-must-run-under-a-registering-instrumen 
    - https://stackoverflow.com/questions/54222533/build-local-unit-tests-no-instrumentation-registered-must-run-under-a-register/54648161
- To use Robolectric as the test runner to provide an Instrumentation Context for the GrantPermissionRule

One or both of the following may help
- https://stackoverflow.com/questions/49791104/how-do-i-create-test-assets-and-grant-runtime-permissions-in-androidtest-tests
- https://stackoverflow.com/questions/49040071/runtimeexception-unable-to-create-output-dir-storage-emulated-0-app-spoon-scr
